---
# tasks file for frr

- name: Installing epel-release
  yum:
    name: epel-release
    state: latest

- name: Installing FRR
  yum:
    name: frr
    state: latest

- name: Enabling ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
