---
# tasks file for bird

- name: Installing epel-release
  yum:
    name: epel-release
    state: latest

- name: Installing BIRD
  yum:
    name: bird
    state: latest

- name: Enabling ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
