# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/postfix.yml"
    ansible.become = "true"
  end

  config.vm.define "postfix" do |postfix|
  postfix.vm.hostname = "postfix"
  postfix.vm.box = "centos/7"
  postfix.vm.box_check_update = false
  postfix.vm.network "private_network", ip: "172.16.10.10"
  postfix.vm.provider :virtualbox do |vb|
    vb.name = "mail.test.ru"
    vb.memory = 512
    vb.cpus = 1
    end
    postfix.vm.provision "shell", run: "always", inline: <<-SHELL
    ### Добавляем пользователя и группу для обработки почтовых каталогов
    groupadd -g 5000 vmail
    useradd -r -u 1150 -g mail -d /var/vmail -s /sbin/nologin -c "Virtual maildir handler" vmail
    ### Создаем и меняем права на каталог для почты
    mkdir /var/vmail
    chmod 770 /var/vmail/
    chown vmail:mail /var/vmail/

    ### Создаем базу данных для работы postfix
    mysql -uroot -e "create database postfix;"
    ### Создаем пользователя postfixuser и задаем ему права
    mysql -uroot -e "create user 'postfixuser'@'localhost' identified by 'postfix';"
    mysql -uroot -e "grant all privileges on postfix.* to postfixuser@'localhost' identified by 'postfix';"
    mysql -uroot -e "flush privileges;"
    ### Заливаем в базу дамп
    mysql -uroot postfix < /root/postfix.sql

    ### Формируем базу данных postfix
    touch /etc/postfix/recipient_access
    postmap /etc/postfix/recipient_access
    service postfix restart

    ### Меняем права на каталоги dovecot
    chown -R vmail:dovecot /etc/dovecot/
    chmod -R o-rwx /etc/dovecot/
    chown -R dovecot:mail /var/log/dovecot
    chmod 777 /var/log/dovecot
    service dovecot restart
    SHELL
  end
end
