---
- name: Install Java
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Add Elasticsearch repo
  yum_repository:
    name: elasticsearch-6.x
    description: Elasticsearch repository for 6.x packages
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes
    enabled: true

- name: Install Elasticsearch package
  yum:
    name: elasticsearch
    state: present

- name: Check elasticsearch.service
  systemd:
    state: started
    name: elasticsearch
    enabled: yes

- name: Install filebeat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.4.0-x86_64.rpm
    state: present

- name: Ensure that Filebeat is configured properly
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

- name: Check filebeat.service
  systemd:
    state: started
    name: filebeat
    enabled: yes

- name: Install Kibana package
  yum:
    name: kibana
    state: present

- name: Ensure that Kibana is configured properly
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml

- name: Check kibana.service
  systemd:
    state: started
    name: kibana
    enabled: yes

- name: Install Logstash
  yum:
    name: logstash
    state: present

- file:
    path: /etc/logstash/patterns
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Install logstash-input-journald
  shell: /usr/share/logstash/bin/logstash-plugin install logstash-input-journald

- name: Ensure that Logstash is configured properly
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'logstash/02-beats-input.conf.j2', dest: '/etc/logstash/conf.d/02-beats-input.conf' }
    - { src: 'logstash/11-nginx-filter.conf.j2', dest: '/etc/logstash/conf.d/11-nginx-filter.conf' }
    - { src: 'logstash/12-nginx-error-filter.conf.j2', dest: '/etc/logstash/conf.d/12-nginx-error-filter.conf' }
    - { src: 'logstash/13-secure-output.conf.j2', dest: '/etc/logstash/conf.d/13-secure-output.conf' }
    - { src: 'logstash/14-mysql-output.conf.j2', dest: '/etc/logstash/conf.d/14-mysql-output.conf' }
    - { src: 'logstash/15-php-output.conf.j2', dest: '/etc/logstash/conf.d/15-php-output.conf' }
#    - { src: 'logstash/16-journald-output.conf.j2', dest: '/etc/logstash/conf.d/16-journald-output.conf' }
    - { src: 'logstash/17-rsyslog-output.conf.j2', dest: '/etc/logstash/conf.d/17-rsyslog-output.conf' }
    - { src: 'logstash/patterns/nginx.j2', dest: '/etc/logstash/patterns/nginx' }
    - { src: 'logstash/patterns/nginx-error.j2', dest: '/etc/logstash/patterns/nginx-error' }

- name: Check logstash.service
  systemd:
    state: started
    name: logstash
    enabled: yes
