# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
 :testBond1 => {
        :box_name => "centos/7",
        :net => [
          {adapter: 2, auto_config: false, virtualbox__intnet: "bond"},
          {adapter: 3, auto_config: false, virtualbox__intnet: "bond"},
                ]
  },

 :testBond2 => {
       :box_name => "centos/7",
        :net => [
          {adapter: 2, auto_config: false, virtualbox__intnet: "bond"},
          {adapter: 3, auto_config: false, virtualbox__intnet: "bond"},
          {adapter: 4, auto_config: false, virtualbox__intnet: "team"},
          {adapter: 5, auto_config: false, virtualbox__intnet: "team"},
                ]
  },

  :testBond3 => {
    :box_name => "centos/7",
     :net => [
       {adapter: 2, auto_config: false, virtualbox__intnet: "team"},
       {adapter: 3, auto_config: false, virtualbox__intnet: "team"},
             ]
  },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "testBond1"
          box.vm.hostname = 'testBond1'
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            cp /vagrant/ifcfg-testbond1  /etc/sysconfig/network-scripts/ifcfg-bond0
            cp /vagrant/ifcfg-eth1.testbond /etc/sysconfig/network-scripts/ifcfg-eth1
            cp /vagrant/ifcfg-eth2.testbond /etc/sysconfig/network-scripts/ifcfg-eth2
            sysctl -w net.ipv4.ip_forward=1
            echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
            systemctl restart network
            SHELL

        when "testBond2"
            box.vm.hostname = 'testBond2'
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              cp /vagrant/ifcfg-testbond2  /etc/sysconfig/network-scripts/ifcfg-bond0
              cp /vagrant/ifcfg-eth1.testbond /etc/sysconfig/network-scripts/ifcfg-eth1
              cp /vagrant/ifcfg-eth2.testbond /etc/sysconfig/network-scripts/ifcfg-eth2
              cp /vagrant/ifcfg-team1 /etc/sysconfig/network-scripts/ifcfg-team0
              cp /vagrant/ifcfg-eth3.team /etc/sysconfig/network-scripts/ifcfg-eth3
              cp /vagrant/ifcfg-eth4.team /etc/sysconfig/network-scripts/ifcfg-eth4
              sysctl -w net.ipv4.ip_forward=1
              echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
#              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              systemctl restart network
               SHELL

          when "testBond3"
             box.vm.hostname = 'testBond3'
             box.vm.provision "shell", run: "always", inline: <<-SHELL
#                echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
                cp /vagrant/ifcfg-team2 /etc/sysconfig/network-scripts/ifcfg-team0
                cp /vagrant/ifcfg-eth1.team /etc/sysconfig/network-scripts/ifcfg-eth1
                cp /vagrant/ifcfg-eth2.team /etc/sysconfig/network-scripts/ifcfg-eth2
                systemctl restart network
                SHELL
        end

      end

  end

end
