global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: '127.0.0.1:25'
  smtp_from: 'prometheus@test.ru'

route:
  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  group_by: ['alertname', 'cluster', 'service']

  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first.
  # notification.
  group_wait: 30s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 5m

  # A default receiver
  receiver: telegram-webhook

receivers:
- name: 'telegram-webhook'
  webhook_configs:
  - url: http://host.example:9119/alert
    send_resolved: true
    http_config:
      basic_auth:
        username: 'alertman'
        password: '12345678'
