{% raw %}
global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
        - 127.0.0.1:9093

rule_files:
    - http_alarm_rules.yml
    - nginx-proxy_alarm_rules.yml
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker-host'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'cadvisor'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'ya.ru-site'
    metrics_path: /probe
    params:
      module:
        - http_2xx
        - icmp
    static_configs:
      - targets:
        - https://ya.ru/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: 'habr.com-http'
    metrics_path: /probe
    params:
      module:
        - http_2xx
        - icmp
    static_configs:
      - targets:
        - https://habr.com/
#        - https://www.site.ru/api/users/
#        - https://www.site.ru/api/users/
#        - https://www.site.ru/api/users/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: 'nginx-proxy1'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.64.30:9113']

  - job_name: 'nginx-proxy2'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.64.31:9113']

  - job_name: 'nginx-proxy3'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.64.32:9113']

  - job_name: 'nginx-proxy4'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.64.33:9113']
{% endraw %}
