---
- name: Update
  yum:
   update_cache: yes
  tags:
    - common

#- name: Upgrade
#  yum:
#    name: '*'
#    state: latest
#  tags:
#    - common

- name: Install common packages
  yum:
    name: ['epel-release', 'git', 'yum-utils', 'device-mapper-persistent-data', 'lvm2', 'wget']
    state: latest
