# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/8"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/routing.yml"
    ansible.become = "true"
  end

  config.vm.define "r1" do |r1|
    r1.vm.hostname = "r1"
    r1.vm.network "private_network", ip: "10.0.0.1", adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "area0"
    r1.vm.network "private_network", ip: "10.10.0.1", adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "area1"
    r1.vm.network "private_network", ip: "10.30.0.1", adapter: 4, netmask: "255.255.255.0"
    r1.vm.provider :virtualbox do |vb|
      vb.name = "r1"
	  vb.memory = 256
    end
  end

  config.vm.define "r2" do |r2|
    r2.vm.hostname = "r2"
    r2.vm.network "private_network", ip: "10.0.0.2", adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "area0"
    r2.vm.network "private_network", ip: "10.20.0.2", adapter: 3, netmask: "255.255.255.252",  virtualbox__intnet: "area2"
    r2.vm.network "private_network", ip: "172.30.0.1", adapter: 4, netmask: "255.255.255.252",  virtualbox__intnet: "bgp1"
    r2.vm.provider :virtualbox do |vb|
      vb.name = "r2"
	  vb.memory = 256
    end
  end

  config.vm.define "r3" do |r3|
    r3.vm.hostname = "r3"
    r3.vm.network "private_network", ip: "10.10.0.2", adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "area1"
    r3.vm.network "private_network", ip: "10.20.0.1", adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "area2"
    r3.vm.network "private_network", ip: "172.20.2.1", adapter: 4, netmask: "255.255.255.0"
    r3.vm.provider :virtualbox do |vb|
      vb.name = "r3"
      vb.memory = 256
    end
  end

  config.vm.define "r4" do |r4|
    r4.vm.hostname = "r4"
    r4.vm.network "private_network", ip: "172.30.0.2", adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "bgp1"
    r4.vm.network "private_network", ip: "172.20.2.1", adapter: 3, netmask: "255.255.255.0"
    r4.vm.provider :virtualbox do |vb|
      vb.name = "r4"
      vb.memory = 256
    end
  end

end
