---
# tasks file for router3

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive

- name: Copy frr configs
  copy:
    src: "{{ item }}"
    dest: /etc/frr
  loop:
    - daemons
    - ospfd.conf
    - zebra.conf

- name: starting and add frr to startup
  systemd:
    name: 'frr'
    state: started
    enabled: yes
