---
# tasks file for quagga

- name: Installing epel-release
  yum:
    name: epel-release
    state: latest

- name: Installing Quagga
  yum:
    name: quagga
    state: latest

- name: Enabling ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
