# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'


Vagrant.configure("2") do |config|

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/apparmor.yml"
    ansible.become = "true"
  end

  config.vm.define "apparmor" do |config|
  config.vm.hostname = "apparmor"
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "172.16.10.110"
  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    end
    config.vm.provision "shell", run: "always", inline: <<-SHELL
#    apt install -y mc net-tools nmap htop iftop
    SHELL
  end
end
