---
- name: Installing epel-release
  yum:
    name: epel-release
    state: latest

### Установка инструментов для работы с SELinux
- name: 'Installing SELinux tools'
  yum:
    name: ['setools-console', 'policycoreutils-python']
    state: latest

### Установка репозитория Percona
- name: Install Percona repository
  yum:
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    state: present

### Установка Percona-Server и сопутствующих пакетов
- name: Install Percona-Server
  yum:
    name: Percona-Server-server-57
    state: present

- name: Install Percona-Server-client
  yum:
    name: Percona-Server-client-57
    state: present

- name: Install Percona-Server-shared
  yum:
    name: Percona-Server-shared-57
    state: present

- name: Install percona-xtrabackup-24
  yum:
    name: percona-xtrabackup-24
    state: latest

- name: Add Percona mysqld.cnf
  template:
    src=roles/selinux/files/etc/percona-server.conf.d/mysqld.cnf
    dest=/etc/percona-server.conf.d/mysqld.cnf

- name: Add Percona my.cnf
  template:
    src=roles/selinux/files/etc/my.cnf
    dest=/etc/my.cnf

### Запуск и включение сервиса mysql в автозагрузку
- name: Check mysqld.service
  systemd:
    state: started
    name: mysql
    enabled: yes

### Установка репозитория nginx
- name: Add nginx repository
  template:
    src=roles/selinux/files/nginx.repo
    dest=/etc/yum.repos.d/nginx.repo

### Установка пакета nginx
- name: 'Installing nginx'
  yum:
    name: nginx
    state: latest

- name: Add nginx configs
  template:
    src=roles/selinux/files/etc/nginx/nginx.conf
    dest=/etc/nginx/nginx.conf

- name: Add nginx conf.d default
  template:
    src=roles/selinux/files/etc/nginx/conf.d/default.conf
    dest=/etc/nginx/conf.d/default.conf

- name: Add nginx conf.d mysite.conf
  template:
    src=roles/selinux/files/etc/nginx/conf.d/mysite.conf
    dest=/etc/nginx/conf.d/mysite.conf

### Запуск и включение сервиса nginx в автозагрузку
- name: Check nginx.service
  systemd:
    state: started
    name: nginx
    enabled: yes

### Установка репозитория REMI
- name: Add REMI repository Centos
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

### Устанавливаем PHP
- name: 'Installing php'
  yum:
    name: ['php-fpm', 'php-cli', 'php-common']
    state: latest

#- name: Add php-fpm.d conf
#  template:
#    src=roles/selinux/files/etc/php-fpm.d/www.conf
#    dest=/etc/php-fpm.d/www.conf

### Запуск и включение сервиса php-fpm в автозагрузку
- name: Check php-fpm.service
  systemd:
    state: started
    name: php-fpm
    enabled: yes

### Установка samba
- name: 'Installing samba'
  yum:
#    name: ['samba', 'system-config-samba']
    name: samba
    state: latest

### Запуск и включение сервиса smb в автозагрузку
- name: Check smb.service
  systemd:
    state: started
    name: smb
    enabled: yes

### Запуск и включение сервиса nmb в автозагрузку
- name: Check nmb.service
  systemd:
    state: started
    name: nmb
    enabled: yes
