---
- name: Install apparmor-utils
  apt:
    name: apparmor-utils
    state: present

- name: Install apparmor-profiles
  apt:
    name: apparmor-profiles
    state: present

- name: Install auditd
  apt:
    name: auditd
    state: present

- name: Copy file with owner and permission, using symbolic representation
  copy:
    src: templates/percona-release_latest.xenial_all.deb
    dest: /tmp/percona-release_latest.xenial_all.deb

### Установка репозитория Percona
- name: Install Percona repository
  apt:
    deb: /tmp/percona-release_latest.xenial_all.deb

### Установка Percona-Server и сопутствующих пакетов
- name: Install Percona-Server
  apt:
    name: percona-server-server-5.7
    update_cache: yes
    state: present

- name: Install Percona-Server-client
  apt:
    name: percona-server-server-5.7
    state: present

- name: Install Percona-Server-shared
  apt:
    name: percona-server-server-5.7
    state: present

- name: Add Percona mysqld.cnf
  template:
    src=roles/apparmor/templates/etc/percona-server.conf.d/mysqld.cnf
    dest=/etc/mysql/percona-server.conf.d/mysqld.cnf

- name: Add Percona my.cnf
  template:
    src=roles/apparmor/templates/etc/my.cnf
    dest=/etc/alternatives/my.cnf

### Запуск и включение сервиса mysql в автозагрузку
- name: Check mysqld.service
  systemd:
    state: started
    name: mysql
    enabled: yes

### Установка репозитория nginx
- name: Add nginx repository
  template:
    src=roles/apparmor/templates/nginx.list
    dest=/etc/apt/sources.list.d/nginx.list

- name: Install GPG nginx repo key
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present

### Установка пакета nginx
- name: 'Installing nginx'
  apt:
    name: nginx
    update_cache: yes
    state: latest

- name: Add nginx configs
  template:
    src=roles/apparmor/templates/etc/nginx/nginx.conf
    dest=/etc/nginx/nginx.conf

- name: Add nginx conf.d default
  template:
    src=roles/apparmor/templates/etc/nginx/conf.d/default.conf
    dest=/etc/nginx/conf.d/default.conf

### Запуск и включение сервиса nginx в автозагрузку
- name: Check nginx.service
  systemd:
    state: started
    name: nginx
    enabled: yes

- name: Add php repo
  apt_repository:
    repo: ppa:ondrej/php

- name: 'Installing php'
  apt:
    name: ['php7.3-fpm', 'php7.3-cli', 'php7.3-common']
    update_cache: yes
    state: latest

- name: Check php-fpm.service
  systemd:
    state: started
    name: php7.3-fpm
    enabled: yes

- name: Add mysqld apparmor profile
  template:
    src=roles/apparmor/templates/etc/apparmor.d/usr.sbin.mysqld
    dest=/etc/apparmor.d/usr.sbin.mysqld

- file:
    path: /etc/apparmor.d/container
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Add docker-nginx apparmor profile
  template:
    src=roles/apparmor/templates/etc/apparmor.d/container/docker-nginx
    dest=/etc/apparmor.d/container/docker-nginx
