---
# tasks file for utility
- name: Installing epel-release
  yum:
    name: epel-release
    state: latest

- name: 'Installing base utilities: tcpdump, traceroute, telnet, vim, htop, nmap'
  yum:
    name: ['mc', 'net-tools', 'tcpdump', 'mtr', 'traceroute', 'telnet', 'vim', 'htop', 'nmap', 'iperf3']
    state: latest

- file:
  path: /root/.config/mc
    state: directory
    owner: root
    group: root
    mode: 0775

- name: /root/.config/mc/ini
  template:
    src: templates/mc/ini
    dest: /root/.config/mc/ini
    owner: root
    group: root
    mode: '0644'
