---
# tasks file for utility
- name: Installing epel-release
  yum:
    name: epel-release
    state: latest

- name: 'Installing base utilities: tcpdump, traceroute, telnet, vim, htop, nmap'
  yum:
    name: ['mc', 'tcpdump', 'traceroute', 'telnet', 'vim', 'htop', 'nmap']
    state: latest
